{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nier-ingest.configMapName" . }}
  labels:
    {{- include "nier-ingest.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Values.configMap.config | nindent 4 }}
{{- end }}
